import Image from 'next/image'
import React, { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'

const Home = () => {

  const [products, setProducts]= useState([])

  useEffect(() => {
    fetch('fakeData.json')
      .then(res => res.json())
      .then(data => setProducts(data))
  }, [])

  return (
    <div>
      <Head>
        <title>Back-Pack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/cart-shopping.svg" />
      </Head>

<div className='mx-5 grid grid-cols-3 '>
  {
    products.map(product=><Product key={product.id} product={product}></Product>)
  }
</div>


    </div>
  )
}


const Product =(props)=>{

  return(
    <div className='border border-black m-3 text-center p-3'>
       
        <Image src={props.product.img} width={400} height={400} alt='this is a img' ></Image>
        <p>{props.product.name}</p>
        <button className='border border-black px-2 rounded-sm'><Link  href={`/products/${props.product.id}`}><a href="">Show Details</a></Link></button>
       
    </div>
  )
}

export default Home
